"""empty message

Revision ID: 12feb9fabf9
Revises: 2a30b4e3e4b
Create Date: 2018-05-11 13:46:48.717674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12feb9fabf9'
down_revision = '2a30b4e3e4b'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
