"""empty message

Revision ID: 192d43ddc4
Revises: 4d3b553297d
Create Date: 2018-05-10 14:57:22.707989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192d43ddc4'
down_revision = '4d3b553297d'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
