"""empty message

Revision ID: 2a30b4e3e4b
Revises: fce6979797
Create Date: 2018-05-11 13:39:25.776902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a30b4e3e4b'
down_revision = 'fce6979797'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('CATEGORY', 'expenses', 'categorys', ['category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CATEGORY', 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'category_id')
    ### end Alembic commands ###
