"""empty message

Revision ID: 2d3b4998649
Revises: 3a64e3e6700
Create Date: 2018-05-10 13:58:35.465776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3b4998649'
down_revision = '3a64e3e6700'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_category', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('USER', 'sub_category', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('USER', 'sub_category', type_='foreignkey')
    op.drop_column('sub_category', 'user_id')
    ### end Alembic commands ###
