"""empty message

Revision ID: 40776c6ce2f
Revises: 4bf8cbb6141
Create Date: 2018-05-08 15:39:37.285898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40776c6ce2f'
down_revision = '4bf8cbb6141'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('item', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], name='SUBCATEGORY'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    ### end Alembic commands ###
