"""empty message

Revision ID: 47eabf3840e
Revises: 491342ccb9f
Create Date: 2018-05-10 13:54:49.340638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47eabf3840e'
down_revision = '491342ccb9f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorys', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('sub_category', sa.Column('created_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_category', 'created_at')
    op.drop_column('categorys', 'created_at')
    ### end Alembic commands ###
