"""empty message

Revision ID: 491342ccb9f
Revises: 3be39473fed
Create Date: 2018-05-10 13:45:50.523243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491342ccb9f'
down_revision = '3be39473fed'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key('USER', 'expenses', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('USER', 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'user_id')
    ### end Alembic commands ###
