"""empty message

Revision ID: 4bf8cbb6141
Revises: 43a30baa193
Create Date: 2018-05-08 14:42:57.429444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf8cbb6141'
down_revision = '43a30baa193'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_category', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key('CATEGORY', 'sub_category', 'categorys', ['category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('CATEGORY', 'sub_category', type_='foreignkey')
    op.drop_column('sub_category', 'category_id')
    ### end Alembic commands ###
