"""empty message

Revision ID: 4d3b553297d
Revises: 4e49f693bab
Create Date: 2018-05-10 14:47:12.504093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3b553297d'
down_revision = '4e49f693bab'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
