"""empty message

Revision ID: 4e49f693bab
Revises: 2d3b4998649
Create Date: 2018-05-10 14:38:53.725136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e49f693bab'
down_revision = '2d3b4998649'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
